GET http://localhost:8081/api/posts/1

POST http://localhost:8081/api/posts
Content-Type: application/json
{
    "id": 4,
    "title":"",
    "body": ""
}

PUT http://localhost:8081/api/posts
Content-Type: application/json
{
    "id": 4,
    "title":"",
    "body": ""
}

DELETE http://localhost:8081/api/posts/1